<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net10.0;net9.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<Version>1.3.2-optiq06</Version>
		<Title>Shell view for Avalonia</Title>
		<Description>Shell reduces the complexity of mobile/desktop application development by providing the fundamental features that most applications require</Description>
		<Copyright>AvaloniaInside</Copyright>
		<PackageProjectUrl>https://github.com/AvaloniaInside/Shell</PackageProjectUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<RepositoryUrl>https://github.com/AvaloniaInside/Shell</RepositoryUrl>
		<PackageTags>avalonia,shell</PackageTags>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	</PropertyGroup>
	<PropertyGroup Condition="$(Configuration) == 'Release'">
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<IncludeSource>True</IncludeSource>
		<IncludeSymbols>True</IncludeSymbols>

		<!-- include the .pdb files in the package. this is not recommended, but has to be done when distributing via Azure Artifacts
      see: https://github.com/dotnet/sourcelink#alternative-pdb-distribution -->
		<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>

		<!-- Optional: Publish the repository URL in the built .nupkg (in the NuSpec <Repository> element) -->
		<PublishRepositoryUrl>true</PublishRepositoryUrl>

		<!-- Optional: Embed source files that are not tracked by the source control manager in the PDB -->
		<EmbedUntrackedSources>true</EmbedUntrackedSources>

		<!-- Optional: Build symbol package (.snupkg) to distribute the PDB containing Source Link -->
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
		<AvaloniaResource Include="**\*.axaml" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
		<PackageReference Include="ReactiveUI.Avalonia" Version="11.3.8" />
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
	  <UpToDateCheckInput Remove="Assets\avalonia-logo.ico" />
	</ItemGroup>
	<ItemGroup>
	  <None Include="..\..\README.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>
</Project>
